/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from "@tanstack/react-router";

// Import Routes

import { Route as rootRoute } from "./routes/__root";

// Create Virtual Routes

const RegisterLazyImport = createFileRoute("/register")();

// Create/Update Routes

const RegisterLazyRoute = RegisterLazyImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/register.lazy").then((d) => d.Route));

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/register": {
      id: "/register";
      path: "/register";
      fullPath: "/register";
      preLoaderRoute: typeof RegisterLazyImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/register": typeof RegisterLazyRoute;
}

export interface FileRoutesByTo {
  "/register": typeof RegisterLazyRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/register": typeof RegisterLazyRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/register";
  fileRoutesByTo: FileRoutesByTo;
  to: "/register";
  id: "__root__" | "/register";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  RegisterLazyRoute: typeof RegisterLazyRoute;
}

const rootRouteChildren: RootRouteChildren = {
  RegisterLazyRoute: RegisterLazyRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/register"
      ]
    },
    "/register": {
      "filePath": "register.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
